### ISSUE TITLE
I just converted the Forester sources into LaTex

### ISSUE THREAD

**Issue by fisheryv** [thosgood/fga#1]
Thanks for your hard work. FGA is very important, and I have converted it into LaTeX code. Please check it [here](https://github.com/fisheryv/fga).

**Comment by thosgood** [comment]
Thank you! Literally a few hours before you commented this, I commited https://github.com/thosgood/fga/commit/3637812ef6ef26fd130ff0ae6a9bace6756a911d which I'm treating as the "official" PDF version. But it's great to have another version around as well! There are a few typos that have come from the tex shortcuts I was using though (e.g. on page 3 I think `\Gamma` has been parsed as `{\Ga}mma`).

Would you mind adding your name to your PDF somewhere (maybe next to "translated by Tim Hosgood") just to avoid any confusion if somebody gets hold of both copies?

**Comment by fisheryv** [comment]
I'm delighted that the official PDF translation is now available. As per your advice, I've included a statement on the cover specifying the source of the adaptation, along with a link to the official version.
